### ISSUE TITLE
feature request: headless mode for jenkins

### ISSUE THREAD

**Issue by kibotu** [asystat/Final-Android-Resizer#11]
as a developer i want to be able to resize assets via command line so that it can be automated via jenkins build step

**Comment by surfer190** [comment]
@kibotu This isn't a bug in this package. You can automate by adding a build step:

`java -jar Resizer-1.4.0.jar /path/to/images`

**Comment by kibotu** [comment]
totally forgot to reply: awesome thanks ^^'
